version: '3'

services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - db.env
    volumes:
      - data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - app-network
  frontend:
    build: ../frontend
    command: pnpm start
    ports:
      - "3000:3000"
    env_file:
      ../frontend/.env
    networks:
      - app-network
    depends_on:
      - backend
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./:/usr/src/app/
    ports:
      - "8000:8000"
    env_file:
      - ./.env.dev
    depends_on:
      - db
    networks:
      - app-network
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  data:
    driver: local

networks:
  app-network:
    driver: bridge