services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - "5432:5432"
    env_file:
      - ./django/db.env
    volumes:
      - data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
    networks:
      - app-network
  nuxt:
    build: ./nuxt
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    env_file:
      ./nuxt/.env
    networks:
      - app-network
    depends_on:
      - django
  django:
    build: ./django
    command: sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    env_file:
      - ./django/.env
    depends_on:
      - db
    networks:
      - app-network
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - app-network

volumes:
  data:
    driver: local

networks:
  app-network:
    driver: bridge
