services:
  db:
    image: postgres:latest
    restart: unless-stopped
    ports:
      - 5432:5432
    env_file:
      - .env
    volumes:
      - data:/var/lib/postgresql/data
    command: ["postgres", "-c", "log_statement=all"]
        
  adminer:
    image: adminer:latest
    restart: unless-stopped
    ports:
      - 8080:8080
 
volumes:
  data:
